
/*
Auto-generated by CVXPYgen on May 15, 2026 at 17:05:33.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Psqrt(0, 1.00000000000000000000);
  cpg_update_Qsqrt(0, 1.00000000000000000000);
  cpg_update_Rsqrt(0, 0.31622776601683794118);
  cpg_update_A(0, 1.00000000000000000000);
  cpg_update_B(0, 0.00000000000000000000);
  cpg_update_x_init(0, 2.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<258; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<126; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<252; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<126; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<6; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }

  return 0;

}
