#ifndef FPGA_PARAMS_H
#define FPGA_PARAMS_H

/* Platform-specific addresses */

#define ADMM_IP_CONTROL_BASE   0xA0000000 
#define ADMM_IP_CONTROL_R_BASE 0xA0010000
#define MAP_SIZE               0x20000UL
#define MAP_MASK               (MAP_SIZE - 1)


/* control registers: scalars */
#define XADMM_CONTROL_ADDR_AP_CTRL                      0x00
#define XADMM_CONTROL_ADDR_GIE                          0x04
#define XADMM_CONTROL_ADDR_IER                          0x08
#define XADMM_CONTROL_ADDR_ISR                          0x0c
#define XADMM_CONTROL_ADDR_NUM_ROWS_DATA                0x10
#define XADMM_CONTROL_BITS_NUM_ROWS_DATA                32
#define XADMM_CONTROL_ADDR_NUM_COLS_DATA                0x18
#define XADMM_CONTROL_BITS_NUM_COLS_DATA                32
#define XADMM_CONTROL_ADDR_A_NNZ_DATA                   0x20
#define XADMM_CONTROL_BITS_A_NNZ_DATA                   32
#define XADMM_CONTROL_ADDR_A_NUM_ROW_TILES_DATA         0x28
#define XADMM_CONTROL_BITS_A_NUM_ROW_TILES_DATA         32
#define XADMM_CONTROL_ADDR_A_NUM_COL_TILES_DATA         0x30
#define XADMM_CONTROL_BITS_A_NUM_COL_TILES_DATA         32
#define XADMM_CONTROL_ADDR_AT_NUM_ROW_TILES_DATA        0x38
#define XADMM_CONTROL_BITS_AT_NUM_ROW_TILES_DATA        32
#define XADMM_CONTROL_ADDR_AT_NUM_COL_TILES_DATA        0x40
#define XADMM_CONTROL_BITS_AT_NUM_COL_TILES_DATA        32
#define XADMM_CONTROL_ADDR_P_NUM_ROW_TILES_DATA         0x48
#define XADMM_CONTROL_BITS_P_NUM_ROW_TILES_DATA         32
#define XADMM_CONTROL_ADDR_P_NUM_COL_TILES_DATA         0x50
#define XADMM_CONTROL_BITS_P_NUM_COL_TILES_DATA         32
#define XADMM_CONTROL_ADDR_SIGMA_DATA                   0x58
#define XADMM_CONTROL_BITS_SIGMA_DATA                   32
#define XADMM_CONTROL_ADDR_ALPHA_DATA                   0x60
#define XADMM_CONTROL_BITS_ALPHA_DATA                   32
#define XADMM_CONTROL_ADDR_ADMM_MAX_ITERATIONS_DATA     0x68
#define XADMM_CONTROL_BITS_ADMM_MAX_ITERATIONS_DATA     32
#define XADMM_CONTROL_ADDR_PCG_MAX_ITERATIONS_DATA      0x70
#define XADMM_CONTROL_BITS_PCG_MAX_ITERATIONS_DATA      32
#define XADMM_CONTROL_ADDR_ADAPTIVE_RHO_DATA            0x78
#define XADMM_CONTROL_BITS_ADAPTIVE_RHO_DATA            1
#define XADMM_CONTROL_ADDR_EPS_ABS_DATA                 0x80
#define XADMM_CONTROL_BITS_EPS_ABS_DATA                 32
#define XADMM_CONTROL_ADDR_EPS_REL_DATA                 0x88
#define XADMM_CONTROL_BITS_EPS_REL_DATA                 32
#define XADMM_CONTROL_ADDR_PCG_TOL_FRACTION_DATA        0x90
#define XADMM_CONTROL_BITS_PCG_TOL_FRACTION_DATA        32
#define XADMM_CONTROL_ADDR_ADMM_NUM_ITERATIONS_OUT_DATA 0x98
#define XADMM_CONTROL_BITS_ADMM_NUM_ITERATIONS_OUT_DATA 32
#define XADMM_CONTROL_ADDR_ADMM_NUM_ITERATIONS_OUT_CTRL 0x9c
#define XADMM_CONTROL_ADDR_PCG_NUM_ITERATIONS_OUT_DATA  0xa8
#define XADMM_CONTROL_BITS_PCG_NUM_ITERATIONS_OUT_DATA  32
#define XADMM_CONTROL_ADDR_PCG_NUM_ITERATIONS_OUT_CTRL  0xac
#define XADMM_CONTROL_ADDR_R_PRIM_OUT_DATA              0xb8
#define XADMM_CONTROL_BITS_R_PRIM_OUT_DATA              32
#define XADMM_CONTROL_ADDR_R_PRIM_OUT_CTRL              0xbc
#define XADMM_CONTROL_ADDR_R_DUAL_OUT_DATA              0xc8
#define XADMM_CONTROL_BITS_R_DUAL_OUT_DATA              32
#define XADMM_CONTROL_ADDR_R_DUAL_OUT_CTRL              0xcc
#define XADMM_CONTROL_ADDR_STATUS_OUT_DATA              0xd8
#define XADMM_CONTROL_BITS_STATUS_OUT_DATA              32
#define XADMM_CONTROL_ADDR_STATUS_OUT_CTRL              0xdc


/* control_r registers: arrays and matrices*/
#define XADMM_CONTROL_R_ADDR_A_ROW_IDX_DATA           0x010
#define XADMM_CONTROL_R_BITS_A_ROW_IDX_DATA           64
#define XADMM_CONTROL_R_ADDR_A_COL_PTR_DATA           0x01c
#define XADMM_CONTROL_R_BITS_A_COL_PTR_DATA           64
#define XADMM_CONTROL_R_ADDR_A_VALUES_DATA            0x028
#define XADMM_CONTROL_R_BITS_A_VALUES_DATA            64
#define XADMM_CONTROL_R_ADDR_A_TILE_NNZ_COUNTS_DATA   0x034
#define XADMM_CONTROL_R_BITS_A_TILE_NNZ_COUNTS_DATA   64
#define XADMM_CONTROL_R_ADDR_A_TILE_NNZ_OFFSETS_DATA  0x040
#define XADMM_CONTROL_R_BITS_A_TILE_NNZ_OFFSETS_DATA  64
#define XADMM_CONTROL_R_ADDR_A_TILE_COL_OFFSETS_DATA  0x04c
#define XADMM_CONTROL_R_BITS_A_TILE_COL_OFFSETS_DATA  64
#define XADMM_CONTROL_R_ADDR_A_ROW_IDX_TILED_DATA     0x058
#define XADMM_CONTROL_R_BITS_A_ROW_IDX_TILED_DATA     64
#define XADMM_CONTROL_R_ADDR_A_COL_PTR_TILED_DATA     0x064
#define XADMM_CONTROL_R_BITS_A_COL_PTR_TILED_DATA     64
#define XADMM_CONTROL_R_ADDR_A_VALUES_TILED_DATA      0x070
#define XADMM_CONTROL_R_BITS_A_VALUES_TILED_DATA      64
#define XADMM_CONTROL_R_ADDR_AT_TILE_NNZ_COUNTS_DATA  0x07c
#define XADMM_CONTROL_R_BITS_AT_TILE_NNZ_COUNTS_DATA  64
#define XADMM_CONTROL_R_ADDR_AT_TILE_NNZ_OFFSETS_DATA 0x088
#define XADMM_CONTROL_R_BITS_AT_TILE_NNZ_OFFSETS_DATA 64
#define XADMM_CONTROL_R_ADDR_AT_TILE_COL_OFFSETS_DATA 0x094
#define XADMM_CONTROL_R_BITS_AT_TILE_COL_OFFSETS_DATA 64
#define XADMM_CONTROL_R_ADDR_AT_ROW_IDX_TILED_DATA    0x0a0
#define XADMM_CONTROL_R_BITS_AT_ROW_IDX_TILED_DATA    64
#define XADMM_CONTROL_R_ADDR_AT_COL_PTR_TILED_DATA    0x0ac
#define XADMM_CONTROL_R_BITS_AT_COL_PTR_TILED_DATA    64
#define XADMM_CONTROL_R_ADDR_AT_VALUES_TILED_DATA     0x0b8
#define XADMM_CONTROL_R_BITS_AT_VALUES_TILED_DATA     64
#define XADMM_CONTROL_R_ADDR_P_TILE_NNZ_COUNTS_DATA   0x0c4
#define XADMM_CONTROL_R_BITS_P_TILE_NNZ_COUNTS_DATA   64
#define XADMM_CONTROL_R_ADDR_P_TILE_NNZ_OFFSETS_DATA  0x0d0
#define XADMM_CONTROL_R_BITS_P_TILE_NNZ_OFFSETS_DATA  64
#define XADMM_CONTROL_R_ADDR_P_TILE_COL_OFFSETS_DATA  0x0dc
#define XADMM_CONTROL_R_BITS_P_TILE_COL_OFFSETS_DATA  64
#define XADMM_CONTROL_R_ADDR_P_ROW_IDX_TILED_DATA     0x0e8
#define XADMM_CONTROL_R_BITS_P_ROW_IDX_TILED_DATA     64
#define XADMM_CONTROL_R_ADDR_P_COL_PTR_TILED_DATA     0x0f4
#define XADMM_CONTROL_R_BITS_P_COL_PTR_TILED_DATA     64
#define XADMM_CONTROL_R_ADDR_P_VALUES_TILED_DATA      0x100
#define XADMM_CONTROL_R_BITS_P_VALUES_TILED_DATA      64
#define XADMM_CONTROL_R_ADDR_P_DIAG_DATA              0x10c
#define XADMM_CONTROL_R_BITS_P_DIAG_DATA              64
#define XADMM_CONTROL_R_ADDR_L_IN_DATA                0x118
#define XADMM_CONTROL_R_BITS_L_IN_DATA                64
#define XADMM_CONTROL_R_ADDR_U_IN_DATA                0x124
#define XADMM_CONTROL_R_BITS_U_IN_DATA                64
#define XADMM_CONTROL_R_ADDR_Q_IN_DATA                0x130
#define XADMM_CONTROL_R_BITS_Q_IN_DATA                64
#define XADMM_CONTROL_R_ADDR_RHO_IN_DATA              0x13c
#define XADMM_CONTROL_R_BITS_RHO_IN_DATA              64
#define XADMM_CONTROL_R_ADDR_X_OUT_DATA               0x148
#define XADMM_CONTROL_R_BITS_X_OUT_DATA               64
#define XADMM_CONTROL_R_ADDR_Y_OUT_DATA               0x154
#define XADMM_CONTROL_R_BITS_Y_OUT_DATA               64

#endif // FPGA_PARAMS_H